# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@internal:
    root: openapi/openapi.yaml
  sample@external:
    root: openapi/openapi.yaml
    lint:
      decorators:
        remove-x-internal: on
lint:
  extends:
    - recommended
  plugins:
    - 'https://raw.githubusercontent.com/trungtuan13/public-testing-repo/main/plugins/demo-plugins.js'
  decorators:
    demo/replace-servers-url: error
  rules:
    no-unused-components: warning
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
